### ISSUE TITLE
vue中引入lazy-load-img获取数据后默认图不消失是怎么回事？

### ISSUE THREAD

**Issue by Missup** [1340641314/SeeDownloadImg#6]
我在common.js里面写了lazyload，然后在.vue页面引入，在create的时候调用了它，在watch中处理了下获取的图片数据，然后渲染到页面上的时候，懒加载图片并没有替换成我获取的图片。。。这是为什么呢？

**Comment by lzxb** [comment]
done: true, //页面内所有数据图片加载完成后，是否自己销毁程序，true默认销毁，false不销毁
设置为false就可以了

**Comment by Missup** [comment]
common.js：
![image](https://user-images.githubusercontent.com/12790251/29199415-6af83094-7e7f-11e7-9b7a-727844d361ec.png)
.vue文件：
![image](https://user-images.githubusercontent.com/12790251/29199460-b824bc0c-7e7f-11e7-8f37-058c5cf763fd.png)
![image](https://user-images.githubusercontent.com/12790251/29199471-c9dd0e40-7e7f-11e7-9234-2d10356c73fe.png)

**Comment by Missup** [comment]
我设置的是false。。。。是我赋值有问题么，还是顺序？
![image](https://user-images.githubusercontent.com/12790251/29199503-095e9f98-7e80-11e7-8eec-f9e4923d9001.png)

**Comment by Missup** [comment]
我解决了。。嘻嘻。。。create的时候不能调用，要在watch的时候调用~

**Comment by lzxb** [comment]
createed钩子，元素还没有存在呢。你应该在mounted钩子中初始化

**Comment by lzxb** [comment]
你可以直接使用[vue-lazy-load-img](https://github.com/lzxb/vue-lazy-load-img)

**Comment by Missup** [comment]
恩恩，好的
