### ISSUE TITLE
请教一下，为什么不用监听scroll事件呢？

### ISSUE THREAD

**Issue by yu-sssss** [1340641314/SeeDownloadImg#8]
看到源码是用嵌套的setTimeout一直循环，直到所有图片都加载完。是出于什么考虑呢？

**Comment by lzxb** [comment]
这个是因为如果要基于滚动条监听，要么监听window的滚动条，要么监听某个元素的，就需要增加很多心智的负担和传参，相比之下使用 setTimeout 可以解决这个问题。
